version: '3.9'
services:
  webapisignal:
    image: fizzbuzz
    container_name: fizzbuzzbackdotnet
    ports:
      - "8080:80"        # Map HTTP port
      - "8081:443"       # Map HTTPS port
      - "5000:5000"      # Additional ports
      - "5001:5001"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7001
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Xuan12343@" # for now, it is a developer environment so i am not too strict
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/dockerdemo.pfx"
    volumes:
      - C:\Users\thanc\.aspnet\https:/https/
    depends_on:
      - mssql
    networks:
      - app_network

  nextapp:
    container_name: fizzbuzzfrontnext
    image: fooboofrontnext
    build: 
        context: ../fooboo-realtime-front-next/
        dockerfile: ../fooboo-realtime-front-next/Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000           # Port inside the container
      HOSTNAME: "0.0.0.0"  # Make the server accessible from all interfaces
    volumes:
        - ./certs:/app/certs:ro
    networks:
      - app_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MssqlDevelopingPass12#"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
      MSSQL_PID: "Developer" # Developer edition of MSSQL
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

volumes:
  mssql_data:

networks:
  app_network:
    driver: bridge  